### ISSUE TITLE
musl build fails

### ISSUE THREAD

**Issue by julio641742** [CanonicalLtd/raft#52]
I am packaging this software for VoidLinux, so far it builds for every single architecture except for *-musl. It fails because it does not find the `error.h` header (src/replication.c` line 6) in the musl libc implementation.
Removing that line makes the compiler happy and compiles.

Is this patch good enough?
```
--- src/replication.c	2019-07-17 15:35:04.329935151 -0700
+++ src/replication.c	2019-07-17 15:44:11.922717037 -0700
@@ -3,7 +3,9 @@
 #include "assert.h"
 #include "configuration.h"
 #include "convert.h"
-#include "error.h"
+#ifdef __GLIBC__
+    #include "error.h"
+#endif
 #include "log.h"
 #include "logging.h"
 #include "membership.h"
```

**Comment by freeekanayaka** [comment]
Yes, that looks good. I'm going to prepare a PR myself and merge it. Feel free to open PRs directly next time. Thanks!
